name: run main.py

# on:
#   workflow_dispatch:

on:
  # push:      # run @ every push
  schedule:
    - cron: '0 11 * * 1' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install bs4
          pip install requests
          pip install fpdf
          pip install yake
          pip install python-docx
          pip install pytz
          pip install glob2
          pip install shutils
          pip install Jinja2


      - name: execute py script # run main.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          LOGIN_KEY: ${{ secrets.LOGIN_KEY }}
          FROM_ID: ${{ secrets.FROM_ID }}
          TO_ID: ${{ secrets.TO_ID}}
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"  
          git add . 
          git commit -m "jobs updated"
          git push
